### ISSUE TITLE
Documentation on how to install it.

### ISSUE THREAD

**Issue by indiamcq** [bitfocus/companion-module-allenheath-sq#17]
I'm new to Companion. This module is not included in Companion yet, but I can't find any info on how this is installed in Companion.

If it is around somewhere then I'd be happy to be corrected.

**Comment by McHauge** [comment]
Hi, modules can only be installed when compling the finished application, in order to use this module please take a look at the v2.2.0 betas of companion, it can be downloaded from the same site using the button "beta builds" below the normal download button.

**Comment by indiamcq** [comment]
Thanks for the information. I was thinking it was a plugin rather than a module. It would be good to add some of this information to the documentation. 

I did not find the place you mentioned v2.2.0 betas. No need to answer, it is beyond me for now.

**Comment by maxks** [comment]
Go to bitfocus.io in download page

https://bitfocus.io/user/downloads

and click on  beta builds

![Screenshot_20210405-092751_Chrome.jpg](https://user-images.githubusercontent.com/5967320/113549187-3db71e00-95f1-11eb-8c1e-ff7748556820.jpg)

Download last release (on top of the list). It's contains all modules, beta including.
