### ISSUE TITLE
[BUG] Allen and Heath SQ losing connection or crashing console 

### ISSUE THREAD

**Issue by simongroom112** [bitfocus/companion-module-allenheath-sq#18]
**Describe the bug**
SQ losing connection more often than being connected. 
constant warning in logs saying MIDI error: connect ETIMEOUT (followed by IP) 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac OSX
- Browser [e.g. chrome, safari] safari 
- Companion Version [e.g. 2.0] v2.2.0-fe4003e3-3269

**Additional context**

desk will reconnect if rebooted but will lose connection again after a short
Amount of time

**Comment by maxks** [comment]
Hi @simongroom112 I downloaded the latest Beta (last 4 characters are 3271) - usually use my own beta with fix and new features to test it - and on my MacBook Pro 13 Mid 2014 running Big Sure (11.2.2), Companion and SQ module works fine and didn't lost connection after 30 minutes of continuos use.

Try to verify network connection and reboot console. Sometimes SQ doesn't connect to network and need reboot to re-working.

**Comment by maxks** [comment]
Hi @bird9908 unfortunately the SQ Midi protocol only accepts one connection at a time. MixPad uses a direct TCP / IP connection not based on the Midi protocol and is complicated to implement with Companion due to the lack of documentation.

**Comment by bird9908** [comment]
> Hi @bird9908 unfortunately the SQ Midi protocol only accepts one connection at a time. MixPad uses a direct TCP / IP connection not based on the Midi protocol and is complicated to implement with Companion due to the lack of documentation.

@maxks thank you for the quick reply, I did not know that, Im a noob. So I power cycled the problematic mixer and put it in a new isolated network by itself with just a Laptop, same issue. So the other mixer is completely out of the equation.

**Comment by maxks** [comment]
@bird9908 my SQ5 sometimes can't reach the gateway when a fixed IP is set, it seems not negotiate its IP. So, I change configuration on SQ and set DHCP and it works fine.

**Comment by philjlihp** [comment]
I have similar issues with failed connections and the desk refusing to reconnect without restarting. Really frustrating that the limits of midi and probably with ip configuration on the desk are causing these problems.
I know there is an app on android not written by A&H to control the desk, so there must be some TCP/IP documentation somewhere.

**Comment by maxks** [comment]
@philjlihp usually to know how TCP / IP works you have to put a "packet sniffer" like Wireshark on your network. Patiently write down all packet when using console functions to understand how it works. Needs time and knowledge to perform this.
If you or others find the documentation (which I have searched for) I'm willing to implement the SQ module with direct TCP / IP connection.

Note: I use Companion every day (7/8 hours) with my SQ5 and the module I created for it without any problems. Yes, with the fixed IP sometimes the connection went, but since I set up a DHCP on the console and set the fixed IP for SQ on the router it works perfectly.

**Comment by philjlihp** [comment]
@maxks  The software on android is called Mixing station and is by @davidgiga1993 https://github.com/davidgiga1993/mixing-station-docs or https://dev-core.org/ms-docs/  It supports the SQ so maybe he has some documentation and is willing to share if its not for profit.
