### ISSUE TITLE
Can't See Channels SQ7

### ISSUE THREAD

**Issue by mrolle41** [bitfocus/companion-module-allenheath-sq#20]
I am trying to mute and unmute channels on the Allen&Heath SQ7 but I can't select which channel to unmute. When I trigger a mute command on channel 0 I can see it unmute and mute channel 1 on our board but I can't choose which. I can look in the list of parameters and see the board is connected with zero issues and sending me tons of data like channel volume and parameters. It looks like a UI issue because I am not having any other issues with commands and connectivity. I already made a FB Post and tried everything like updating the SQ7 Firmware but nothing works. One screenshot shows the aux mixes working like normal and the other shows the channels not working.
[
![Companion Issue2](https://user-images.githubusercontent.com/85421803/120909757-6cc82b00-c646-11eb-9f1b-b07e2aaba178.PNG)
![Companion Issue1](https://user-images.githubusercontent.com/85421803/120909758-6cc82b00-c646-11eb-934b-684d541583f7.PNG)

](url)

**Comment by maxks** [comment]
Hi @mrolle41 if module works correctly it show channel choices like this:

<img width="545" alt="input_choices" src="https://user-images.githubusercontent.com/5967320/120919044-dfbdba00-c6b7-11eb-9eeb-7c9b38926be5.png">

To understand why you has this issue I need to know:

1) firmware version of your SQ7
2) Companion version

Have you tried removing and then adding the module again?

> sending me tons of data like channel volume and parameters. 

At startup is a normal procedure to permit Companion module to retrieve current console status.

**Comment by mrolle41** [comment]
Ok

**Comment by stephenbrokalis** [comment]
Hi @maxks. I work with @mrolle41 so we are trying to figure this out together

To Answer your question we are using the latest version of Companion and we were on an old SQ7 firmware update but we updated to the latest version but that unfortunately didn’t fix anything so the board itself isn’t the issue.

We have had this issue for about a month and in that time we have removed the module and re-added it several times, enabled it, disabled it, etc… we even tried installing companion on multiple computers and they all have this same issue but communicate and connect to the console just fine.

Again the console and companion are talking to eachother, I mute and unmute aux sends, DCA groups, etc… with ease.

There is nothing on our end that would indicate that there are any problems.
As far as I know there is a UI glitch with the Allen & Heath module and we are the only ones experiencing it.

**Comment by maxks** [comment]
Hi @stephenbrokalis 
Are you using last beta or last official release?
Have you try to watch log if there are issues?

It seems that upgrade script failed, but my last beta release is older than one month ago (march 29).

**Comment by stephenbrokalis** [comment]
We’re on 2.1.3 which is the latest official release. I will try using it then post a photo(s) of the log.

**Comment by maxks** [comment]
After you'll send me the log image, can you will try to use last beta release? 

(2.2.0 - 3353)

**Comment by stephenbrokalis** [comment]
@maxks I got it working! 
I updated to 2.2.0 beta release but that didn't fix the issue. I looked at the log and it wasn't displaying any errors or anything interesting. Again when I click the button it runs the mute command on channel 0 successfully. It doesn't give me any errors opening the dropdown either.
What fixed the issue was going into instances and changing the Allen&Heath module from SQ7 to SQ6. We have an SQ7 but setting Companion to SQ6 was the only way to get around the issue.

**Comment by maxks** [comment]
@stephenbrokalis thank you for feedback. At this moment, SQ5/6/7 configurations plays same functions. I put all models for future upgrade by A&H midi functionality (like soft rotary).
I will look into code to understand why SQ6 works and SQ7 no.

**Comment by maxks** [comment]
New beta release 1.3.7 fixs SQ7 channels issue.

**Comment by mrolle41** [comment]
Thanks, I'll check it out.
