### ISSUE TITLE
SQ fader and pan stepping

### ISSUE THREAD

**Issue by bensmm** [bitfocus/companion-module-allenheath-sq#28]
Using both you SQ and QU Companion modules for our two A&H desks for church audio and livestream for a number of months now. Working super well, thank you. Just one issue we can’t seem to crack: we cannot get the SQ faders to step +1 dB or -1dB, nor recall last dB level, but absolutely no problem when setting a fader to an absolute level. Same for pan, we can set an absolute position, but step R or step L nothing happens. Fader law is set to match SQ. It’s odd that everything else is working but not the steps. Can you advise if it’s something we are doing wrong / setting incorrectly? Thank you.

**Comment by maxks** [comment]
Hi @bensmm , are you use the official or beta Companion release? What module version do you use (you see that on module info)?
Thanks.

**Comment by bensmm** [comment]
Thank you.  Running Companion in beta 2.2.0 (2.2.0.-fa10056c-3503), so 1.3.8 for the SQ module?

**Comment by maxks** [comment]
@bensmm 1.3.8 is latest release fixing a bug on fader steps. Can you just export the page with the configured +/- 1 buttons not working and send me that file?
I have to investigate this issue. Thanks.

**Comment by bensmm** [comment]
@maxks  Sorry for the delay and thank you for looking into this. Page 3 export here for you. It has test buttons for channel 1 on SQ5. -5 and -39 work with no problem, however, +1 and -1 steps below those have no effect when pushed. (I added .txt as extension to upload.)
[DESKTOP-HB0T8AI_page 3_20210917-2014.companionconfig.txt](https://github.com/bitfocus/companion-module-allenheath-sq/files/7188043/DESKTOP-HB0T8AI_page.3_20210917-2014.companionconfig.txt)
.)

**Comment by bensmm** [comment]
@maxks Thank you, that's great. Will check and report back as soon as beta is available and downloaded.
