### ISSUE TITLE
Nothing past Ch-17 for Mix Assigns On/Off

### ISSUE THREAD

**Issue by ematland** [bitfocus/companion-module-allenheath-sq#29]
Hi, just trying to script some Channel Assign to Mix(es) toggled on/off to send TB and other elements hot to Webcast busses and safe from web cast busses and did my Talkback mic (on channel 17) to Mix 01, Mix 02, Mix 03, 04, 05, and 06 all successfully toggling on and off.  Trying to do the same with other inputs past channel 17.  Channel 17 worked the same but channel 18 and higher don't work at all.  Testing on stream xl, also using test in companion on windows computer and trying web buttons.
Companion version 2.1.3 A&H module 1.3.4

**Comment by maxks** [comment]
You will have to try Companion 2.2.0 (beta version) that it has SQ 1.3.8 module with some bug fixes.
After that give me a feedback, thanks.

**Comment by ematland** [comment]
Hello, so my issue with everything past channel 17 was user error.  My client had their board setup in stereo pairs starting at 17 so all the even numbers (the right side of a stereo pair) had no effect.  The odd numbers did work perfectly for each consecutive pair but I was missing it because I was looking in the wrong place at the time.  

Why does the instance setup page ask about the default Talkback input?  My client's SQ5 has a dedicated Talkback XLR input on it and that's what they use but I don't see anything other than 1-48 as channel inputs.  And then, when programming a button, I don't see anything that is dedicated to Talkback mic programming like on/off or mix group assign.  Are you working towards this?

Thank you for letting me know I'm behind on my companion version.  I'll update and see if anything looks different.  Your module definitely improved the workflow for webcast routing with multiple remote sources.  Thank you.

**Comment by maxks** [comment]
Hi @ematland follow description is cutted from README:

_Talkback
This macro preset simulate the native function talkback of SQ, but it works with "channel assign to mix" function in console routing screen. With this preset you'll be able to talk to one specific AUX channels by pressing a button. This preset works with talkback input channel you set up on instance configuration. Initially, you have to remove the talkback input channel from mix assign on the console._

Input channels 1-48 are defined in the routing section and by default they are set according to the physical inputs, but you will be able to change them as you like. If you route the physical talkback input to channel 1 (example), channel 1 (IP1) can be used in the talkback macro. On the SQ5, the talkback input is one of 17 XLR inputs capable of capturing a signal and only by default is routed to the talkback function on the console. It can be used for other type of input (like vocal mic), just change the routing.
