### ISSUE TITLE
Two Companion instances controlling one SQ5?

### ISSUE THREAD

**Issue by derclaudio** [bitfocus/companion-module-allenheath-sq#35]
Hi,
We tried to setup two companion instances on two different PCs: One for the control room and one at the announcer position to mute and talkback to each other. I get a Midi error back in the log, once a second instance is enabled. Any workaround to access with two companion on one SQ5

**Comment by maxks** [comment]
Is not an issue, you can't connect to two midi instances at same time. The best way is connect to first instance via web browser.
