### ISSUE TITLE
[BUG] Allen & Heath SQ Colour Feedback Not Working Properly in 3.0.0 Stable

### ISSUE THREAD

**Issue by YvonneMV** [bitfocus/companion-module-allenheath-sq#44]
I have upgraded to the latest stable release of 3.0 and have found that in Feedbacks, "Change colour" for the A&H SQ is not working properly for inputs or mute mute groups.  The color change will trigger when the mute is activated, however it does not return to the actions key color/formatting when unmuted.  

In previous versions, the color of the Companion button would always reflect either muted and unmuted states regardless of whether triggered by Companion, directly on the board or through the Mixpad app.  I would appreciate any help that can be provided to resolve this.  Thanks!

- SQ-5: 1.5 r3883
- OS: Win10
- Browser: Chrome 114.0.5735.199
- Companion Version: 3.0.0-rc2+5989-stable-4d17e724

**Comment by petenewk** [comment]
I am experiencing the same issue. It is always showing muted regardless of the true status.

**Comment by Julusian** [comment]
This should be fixed in the 3.0.0 release
