### ISSUE TITLE
Module failing to send Midi out messages for certain actions.

### ISSUE THREAD

**Issue by JoshDarnIt-All** [bitfocus/companion-module-allenheath-sq#54]
*** Means: Non-functional. No feedback in Debug/Log. Looks like there is no Outgoing Message.

Assign Channel to FX send - *** 
Assign Channel to Group - *** 
Assign Channel to Mix - *** 
Assign FX return to FX send - *** 
Assign FX return to Group - *** 
Assign Group to FX Send - *** 
Assign Group to MTX - *** 
Assign Group to Mix - *** 
Assign Mix to MTX - *** 

Using Debug/Log I am not seeing any output from any of these actions. Will update the list as I find more.

**Comment by jswalden** [comment]
I sort of stumbled on this by happenstance, and I know what it is, and I probably have a fix -- once I can get back to a mixer to test it.

**Comment by jswalden** [comment]
This is fixed in f0f3df739750c558dffe2e97912b5bf3984cb35a.  It seems all the multiple-selection options (corresponding to exactly the actions you list)  were defined as

```js
const opt = {
    type: 'dropdown',
    multiple: true,
    // ...
}
```

rather than

```js
const opt = {
    type: 'multidropdown',
    // ...
}
```

and so the option value would be a single value rather than an array of them, with result that a `for (let i = 0; i < mix.length; i++)` loop to send a bunch of MIDI commands to perform the requested assignments would never execute because `0 < undefined` would be `false`.

I can't figure out why these were all misencoded this way.  I grunged through `@companion-module/base` type definitions multiple years back (and before Companion 3.0) and couldn't find a time when multiple-selection options were defined in this other format.  It doesn't really matter, but do you happen to know anything about when this older pattern ended, @josephdadams?  These actions must have worked at _some_ point.

**Comment by josephdadams** [comment]
I really do not know. It is possible it never worked. I am not an SQ user - I just gave my best attempt to convert it to v3 for compatibility. I had a hard time understanding what all was going on!

**Comment by JoshDarnIt-All** [comment]
I have been testing most actions on version 3.3.1. I have 3 main notes that should give a jumping off point. 

1. Any action involving what would be a midi message has no affect on the console, there is also no record of any midi message being sent out via the companion Log. 
Examples of these message types:
Assign Channel to FX send - *** 
Assign Channel to Group - *** 
Assign Channel to Mix - *** 
Assign FX return to FX send - *** 
Assign FX return to Group - *** 
Assign Group to FX Send - *** 
Assign Group to MTX - *** 
Assign Group to Mix - *** 
Assign Mix to MTX - ***  
Etc.


2. Any message involving Levels is not affecting console as well. I have run into this error in the logs for every "Level" based action from the module: 
"24.08.08 10:52:20 Instance/Wrapper/SQMostRecent: Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\",\"internal:time_hms_12\"]}"}"

I am unsure what "Child is not running" means. 

3. All Midi Feedback from Console to Module seems to be funtional. Companion displays fader levels (though it is off by about 15db) and I can see current scene and whatnot. Feedback seems to be happy.

Hopefully this helps!

Had some personal stuff with a new baby and touring work going on, but back at home base and ready to test as needed to get this module functional!

**Comment by JoshDarnIt-All** [comment]
Mute commads are functional.

**Comment by josephdadams** [comment]
"Child is not running" means the module crashed. Sometimes you can see helpful info if you open the ">_" tab next to the SQ module in Connections, it opens what looks like a terminal output. However, sometimes it is not helpful, especially if it's just a long string of red obfuscated/minified code...

**Comment by josephdadams** [comment]
(All modules in Companion v3.x run as child processes independent of the main Companion process. In the prior versions, if a module crashed, it would often take down the whole Companion process with it since everything was shared.)

**Comment by JoshDarnIt-All** [comment]
@josephdadams @jswalden 
I decided to jump back to 2.4.2 to verify that these actions all worked. Every listed action is functional, and the Log is showing these outgoing Midi messages. 

Something about 3.3.1 is blocking these outgoing messages. 

Here is my log from my testing in 2.4.2 below. 
<img width="1015" alt="Screenshot 2024-08-08 at 11 48 59 AM" src="https://github.com/user-attachments/assets/105247e2-dd14-4ed4-a315-0900607fdb59">
