### ISSUE TITLE
[BUG] "lv.fixed" Function causing module lockup/crash 

### ISSUE THREAD

**Issue by JoshDarnIt-All** [bitfocus/companion-module-allenheath-sq#55]
This was first observed using "Fader channel level to FX send" Action. It can be observed with may different actions. Seems to be an issue related to "lv.fixed" being undefined according to the Debug/Log

See Debug/Log attatched below. This function shows a common issue in any action currently using “lv.fixed” function. Error is clearly stated in Debug/Log. When You try to utilize this step, it causes an issue where companion repeatedly restarts module, ultimately crashing the module. During this time you lose all control of console via the companion module. I still have physical control of the console. 

[Fader channel level to FX send - Debug log.csv](https://github.com/bitfocus/companion-module-allenheath-sq/files/15380610/Fader.channel.level.to.FX.send.-.Debug.log.csv)

**Comment by josephdadams** [comment]
should be fixed now
